esp32:
  board: esp32-s3-devkitc-1 # esp32s3box
  variant: esp32s3
  flash_size: 8MB
  cpu_frequency: 240MHz
  framework:
    type: esp-idf
    # version: 5.4.2
    # platform_version: 54.03.21
    sdkconfig_options:
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESPTOOLPY_FLASHSIZE_8MB: "y"
      CONFIG_FREERTOS_HZ: "1000"
      CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ_240: y
      CONFIG_ESPTOOLPY_FLASHMODE_QIO: y
      CONFIG_ESPTOOLPY_FLASHFREQ_120M: y
      CONFIG_SPIRAM_MODE_OCT: y
      CONFIG_IDF_EXPERIMENTAL_FEATURES: y
      CONFIG_SPIRAM_SPEED_120M: y
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: y
      # CONFIG_COMPILER_OPTIMIZATION_SIZE: y
      CONFIG_COMPILER_OPTIMIZATION_PERF: y
      #CONFIG_COMPILER_OPTIMIZATION_DEBUG: y
    advanced:
      enable_idf_experimental_features: True


### Board Configuration
esphome:
  name: ${device_internal_name}
#  min_version: 2025.05.2
  friendly_name: ${device_friendly_name}
  platformio_options:
#    build_unflags: -Werror=all
    board_build.flash_mode: dio
    build_flags: "-DBOARD_HAS_PSRAM"
    board_build.arduino.memory_type: qio_opi
    board_upload.maximum_ram_size: 524288
    #board_build.flash_size: 8MB #Added
    # No second OTA partition. Must be flashed through serial (hint: ser2net)
#    : board_build.partitions"../../../hmi-garage/custom_partition_no_ota.csv"
    #board_build.partitions: ../../../default_8MB.csv #partitions.csv
    #board_build.partitions: ../../../custom_partition_no_ota.csv #partitions.csv
  # on_boot:
  #   priority: -100
  #   then:
  #     - delay: 10min
  #     - lambda: |-
  #         if (id(temp_sensor).state == NAN) {
  #           ESP.restart();
  #         }

 
### Enable logging
logger:
  # level: INFO 
  level: WARN  # або ERROR
  logs:
    sensor: ERROR
    api.service: ERROR

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: NONE
  reboot_timeout: 15min
  fast_connect: true


  # Enable fallback hotspot (captive portal) in case wifi connection fails
#   ap:
#     ssid: "Waveshare-Esp32-S3-7Inch"
#     password: !secret ota_password

# captive_portal:

ota:
  - platform: esphome
    password: !secret ota_password

### Enable Home Assistant API
api:
  encryption:
    key: "CVLizPM8B8ai0fwgj8qiu558JhQ6ETao5bKPSdsLNPk="
  id: ha_api
  reboot_timeout: 10min 

    
    ## Web Server
web_server:
  port: 80
  version: 2
#   auth:
#   include_internal: true
#     username: !secret web_server_user
#     password: !secret web_server_password
#   local: true

psram:
  mode: octal
  speed: 120MHz

### IO Extender
ch422g:
  - id: ch422g_hub

i2c:
  sda: GPIO08
  scl: GPIO09
  frequency: 400kHz
  scan: True
  id: bus_a


### Time
time:
  - platform: sntp
    id: esptime
    timezone: Europe/Kyiv
  # - platform: homeassistant
  #   id: esptime
    on_time:
      - seconds: 0
        then:
          - lvgl.label.update:
              id: homeassistant_time_text
              text: !lambda |-
                  auto now = id(esptime).now();
                  //const char* days[] = {"Нд", "Пн", "Вт", "Ср", "Чт", "Пт", "Сб"};
                  const char* days[] = {"Su", "Mo", "Tu", "We", "Th", "Fr", "Sa"};
                  char buf[32];
                  sprintf(buf, "%02d:%02d %s %02d/%02d/%04d",
                          now.hour, now.minute,
                          days[now.day_of_week-1],
                          // now.day_of_week,
                          now.day_of_month, now.month, now.year);
                  return std::string(buf);

  - platform: homeassistant
    id: antiburn_time
    on_time:
      - hours: 2,3,4,5
        minutes: 5
        seconds: 0
        then:
          - switch.turn_on: switch_antiburn
          - switch.turn_off: lcdbacklight
      - hours: 2,3,4,5
        minutes: 35
        seconds: 0
        then:
          - switch.turn_off: switch_antiburn
      - hours: 5
        minutes: 50
        seconds: 0
        then:
          - switch.turn_on: lcdbacklight

### Display
display:
  - platform: rpi_dpi_rgb
    id: my_display
    update_interval: never
    auto_clear_enabled: false
    color_order: RGB
    pclk_frequency: 16MHZ
    dimensions:
      width: 800
      height: 480
    reset_pin:
      ch422g: ch422g_hub
      number: 3
#    enable_pin:
#      ch422g: ch422g_hub
#      number: 2  
    de_pin:
      number: 5
    hsync_pin:
      number: 46
      ignore_strapping_warning: true
    vsync_pin:
      number: 3
      ignore_strapping_warning: true
    pclk_pin: 7
    pclk_inverted: true
    hsync_back_porch: 8
    hsync_front_porch: 8
    hsync_pulse_width: 4
    vsync_back_porch: 16
    vsync_front_porch: 16
    vsync_pulse_width: 4
    data_pins:
      red:
        - 1         #r3
        - 2         #r4
        - 42        #r5
        - 41        #r6
        - 40        #r7
      blue:
        - 14        #b3
        - 38        #b4
        - 18        #b5
        - 17        #b6
        - 10        #b7
      green:
        - 39        #g2
        - 0         #g3
        - 45        #g4
        - 48        #g5
        - 47        #g6
        - 21        #g7


### Touchscreen
touchscreen:
  platform: gt911
  id: my_touch
  interrupt_pin: GPIO4
  reset_pin:
    ch422g: ch422g_hub
    number: 1
    mode: OUTPUT
  # on_touch:
  #   - if:
  #       condition: 
  #         switch.is_off: lcdbacklight
  #       then:
  #         switch.turn_on: lcdbacklight 
    # - lambda: |-
    #     ESP_LOGI("Touch", "Touch detected at x=%d, y=%d", touch.x, touch.y);
  # on_update:
  #   - lambda: |-
  #         for (auto touch: touches)  {
  #             if (touch.state <= 2) {
  #               ESP_LOGI("Touch points:", "id=%d x=%d, y=%d x.raw=%d, y.raw=%d", touch.id, touch.x, touch.y, touch.x_raw, touch.y_raw);
  #             }
  #         }  


  # on_release:
  #   then:
  #     - if:
  #         condition: lvgl.is_paused
  #         then:
  #           - lvgl.resume:
  #           - lvgl.widget.redraw:
output:
  - platform: gpio 
    pin: GPIO6
    id: thermo_relay_pin